name = "LogRollerCompose"
uuid = "35b68a49-52b3-46cc-a782-1725e63e5e62"
authors = ["Tanmay Mohapatra <tanmaykm@gmail.com>"]
license = "MIT"
desc = "Enable LogRoller for LogCompose"
version = "0.1.0"

[deps]
LogCompose = "8416b438-731e-11ea-2421-05f642269042"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LogRoller = "c41e01d8-14e5-11ea-185b-e7eabed7be4b"

[compat]
julia = "1"
LogRoller = "0.3"
LogCompose = "0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
